version: '3.1'
services:

  rp-redis:
    image: 'redis:7.0'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  rp-wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    restart: always
    command: "--global-response-templating --enable-stub-cors" # add command `--verbose` to output verbose request matching
    ports:
      - "9091:8080"

networks:
  hmpps_int:
