generic-service:
  nameOverride: hmpps-restricted-patients
  productId: DPS066

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-restricted-patients
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-restricted-patients-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  namespace_secrets:
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-restricted-patients:
      AUTH_CODE_CLIENT_ID: 'API_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'API_CLIENT_SECRET'
      CLIENT_CREDS_CLIENT_ID: 'SYSTEM_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'SYSTEM_CLIENT_SECRET'
      SESSION_SECRET: 'SESSION_SECRET'
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  targetApplication: hmpps-restricted-patients
