generic-service:
  nameOverride: hmpps-restricted-patients-ui
  productId: DPS066
  cronPrefixName: ui

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-restricted-patients-ui
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-restricted-patients-cert
    modsecurity_enabled: true
    modsecurity_snippet: |
      SecRuleEngine On
      # team here grants access to the OpenSearch logs to delve into the cause of the blockage
      SecDefaultAction "phase:2,pass,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Default is only GET HEAD POST OPTIONS so need to include PUT etc.
      SecAction "id:900200,phase:1,nolog,pass,t:none,setvar:tx.allowed_methods=GET HEAD POST OPTIONS PUT PATCH DELETE,setvar:tx.paranoia_level=3"
      # Block Detectify scanner with 418
      SecRule REQUEST_HEADERS:User-Agent "@pm detectify Detectify DETECTIFY" "id:800003,phase:1,deny,status:418,log,tag:github_team=syscon-devs,tag:namespace={{ .Release.Namespace }}"
      # Change default denial to be a 406 so that we can tell easily that it is modsecurity doing the blocking
      SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
      SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    LOG_LEVEL: 'info'
    REDIS_ENABLED: "true"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"

  namespace_secrets:
    hmpps-restricted-patients-ui-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-restricted-patients-ui-auth-code:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'
    hmpps-restricted-patients-ui-client-creds:
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-restricted-patients-ui-session-secret:
      SESSION_SECRET: 'SESSION_SECRET'
    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: syscon
  targetApplication: hmpps-restricted-patients-ui
