---
# Per environment values which override defaults in hmpps-restricted-patients/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-restricted-patients-preprod.hmpps.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '27 6 * * 1-5' # Start at 6.27am UTC Monday-Friday
    shutdown: '44 21 * * 1-5' # Stop at 9.44pm UTC Monday-Friday

  env:
    INGRESS_URL: "https://manage-restricted-patients-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    PRISON_API_URL: https://prison-api-preprod.prison.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search-preprod.prison.service.justice.gov.uk
    RESTRICTED_PATIENT_API_URL: https://restricted-patients-api-preprod.hmpps.service.justice.gov.uk
    COMPONENT_API_URL: https://frontend-components-preprod.hmpps.service.justice.gov.uk
    ENVIRONMENT_NAME: PRE-PRODUCTION
    DPS_URL: https://digital-preprod.prison.service.justice.gov.uk
    PRISONER_PROFILE_URL: https://prisoner-preprod.digital.prison.service.justice.gov.uk

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-service-dev

  elastiCacheAlertsClusterIds:
    cp-84615cccbbc1ac52-001: "HMPPS Restricted Patients ElastiCache Cluster Node 1"
    cp-84615cccbbc1ac52-002: "HMPPS Restricted Patients ElastiCache Cluster Node 2"
